<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\css\_variables.less" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotless.Core" Version="1.6.7" ExcludeAssets="all" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
    <PackageReference Include="Radzen.Blazor" Version="11.2.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Components\Layout\NavigationMenu\NavigationMenuResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NavigationMenuResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\AboutSection\AboutSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AboutSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\CoachesSection\CoachesSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CoachesSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\ContactSection\ContactSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContactSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\HallOfFameSection\HallOfFameSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HallOfFameSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\MwkszSection\MwkszSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MwkszSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\WhyUsSection\WhyUsSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WhyUsSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Shared\CompetitorResultsDialog\CompetitorResultsDialogResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CompetitorResultsDialogResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Shared\SenpaiResultsDialog\SenpaiResultsDialogResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SenpaiResultsDialogResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Components\Layout\NavigationMenu\NavigationMenuResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NavigationMenuResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Layout.NavigationMenu</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\AboutSection\AboutSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AboutSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.AboutSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\CoachesSection\CoachesSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CoachesSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.CoachesSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\ContactSection\ContactSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ContactSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.ContactSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\HallOfFameSection\HallOfFameSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>HallOfFameSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.HallOfFameSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\MwkszSection\MwkszSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MwkszSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.MwkszSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\WhyUsSection\WhyUsSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WhyUsSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Pages.WhyUsSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Shared\CompetitorResultsDialog\CompetitorResultsDialogResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CompetitorResultsDialogResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Shared.CompetitorResultsDialog</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Shared\SenpaiResultsDialog\SenpaiResultsDialogResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SenpaiResultsDialogResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Shared.SenpaiResultsDialog</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
</Project>
