<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Pages\TimetableSection - Copy\**" />
    <Content Remove="Components\Pages\TimetableSection - Copy\**" />
    <EmbeddedResource Remove="Components\Pages\TimetableSection - Copy\**" />
    <None Remove="Components\Pages\TimetableSection - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\css\_variables.less" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotless.Core" Version="1.6.7" ExcludeAssets="all" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" PrivateAssets="all" />
    <PackageReference Include="Radzen.Blazor" Version="11.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heiwase.App.Shared\Heiwase.App.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Components\Layout\NavigationMenuResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NavigationMenuResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\AboutSection\AboutSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AboutSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\CoachesSection\CoachesSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CoachesSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\ContactSection\ContactSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContactSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\DojoSection\DojoSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DojoSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\HallOfFameSection\HallOfFameSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HallOfFameSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\MwkszSection\MwkszSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MwkszSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Sections\Home\WhyUsSection\WhyUsSectionResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WhyUsSectionResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Shared\Dialogs\CompetitorResultsDialog\CompetitorResultsDialogResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CompetitorResultsDialogResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Shared\Dialogs\SenpaiResultsDialog\SenpaiResultsDialogResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SenpaiResultsDialogResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewModels\ApplicantModelResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApplicantModelResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Components\Layout\NavigationMenuResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NavigationMenuResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Layout</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\AboutSection\AboutSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AboutSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.AboutSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\CoachesSection\CoachesSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CoachesSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.CoachesSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\ContactSection\ContactSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ContactSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.ContactSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\DojoSection\DojoSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DojoSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.DojoSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\HallOfFameSection\HallOfFameSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>HallOfFameSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.HallOfFameSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\MwkszSection\MwkszSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MwkszSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.MwkszSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Sections\Home\WhyUsSection\WhyUsSectionResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WhyUsSectionResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Sections.Home.WhyUsSection</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Shared\Dialogs\CompetitorResultsDialog\CompetitorResultsDialogResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CompetitorResultsDialogResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Shared.Dialogs.CompetitorResultsDialog</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Shared\Dialogs\SenpaiResultsDialog\SenpaiResultsDialogResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SenpaiResultsDialogResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.Components.Shared.Dialogs.SenpaiResultsDialog</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\ApplicantModelResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ApplicantModelResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Heiwase.App.Blazor.ViewModels</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
</Project>
